version: '3.8'

services:
  web:
    build: .
    container_name: fitarena_django
    restart: always
    env_file:
      - .env
    command: >
      sh -c " pipenv run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - db
      - redis
      - celery

  db:
    image: postgres:15
    container_name: fitarena_postgres
    restart: always
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: fitarena_redis
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: fitarena_celery
    restart: always
    env_file:
      - .env
    command: >
      sh -c "pipenv run celery -A core worker --loglevel=info"
    depends_on:
      - redis
      - db

  nginx:
    image: nginx:latest
    container_name: fitarena_nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
      - ./media:/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
